### ISSUE TITLE
Reading of data that is solved with Cvode not possible

### ISSUE THREAD

**Issue by BenaniZ** [RWTH-EBC/ebcpy#102]
Reading .mat files that are created using the solver Cvode leads to this error:

> File` "...\ebcpy\modelica\simres.py", line 314, in mat_to_pandas
>     values = _variables[name].values(t=times)  # Resample.
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: Variable.values() got an unexpected keyword argument 't'

To reproduce error, simulate in Dymola with solver Cvode or use DymolaAPI and set solver manually to Cvode, since another solver is used by default (probably Dassl). The solver can be set in the simulation setup as follows: _"solver": "Cvode"_
After the simulation, use TimeSeriesData to read the .mat file. Then the error should appear.

**Comment by FWuellhorst** [comment]
Thanks for finding this bug. I think it is related to #69. CVode seems to export infinity as `inf`, DASSL as a large number `1e+308`. `inf` - `inf` in python in `nan`, this is why the code does not correctly finds a constant value and tries to resample it. 

I hopefully fixed it in branch 102.

**Comment by BenaniZ** [comment]
I can confirm that the bug does not appear with the fix in branch 102. Thank you for solving the issue!
