### ISSUE TITLE
calling dymola on linux maschin not working

### ISSUE THREAD

**Issue by Cudok** [RWTH-EBC/ebcpy#115]
problem: not the right call of dymola via ebcpy

  - for running the simulation in dymola the python package ebcpy is used
  - ebcpy calls automaticlly  '/opt/dymola-2023x-x86_64/bin64/dymola' 
    - but here the needed libs are not found
    - it is needed to call  '/opt/dymola-2023x-x86_64/bin64/dymola.sh'
  - solution: edit the file dymola_api.py of the package ebcpy
    -  adapt line 1025: dymola_name = "dymola" > "dymola.sh"

System:
Ubuntu 22.04
dymola-2023x-x86_64

**Comment by FWuellhorst** [comment]
Same as for the `dymola_interface_path`, I would just add the explicit path to the list of kwargs. This solution would not work for our dymola installation, so it seems to depend on the end user. 
Would that work for you as well?

**Comment by Cudok** [comment]
Do you mean I should add the kwarg dymola_interface_path to DymolaAPI()?
 I tried to use dymola_path  here. but it does not work.
Now, I tried he kwarg dymola_interface_path as well, but it does not work too.

When dymola.sh is called, also the pathes of the libs are added. From my point of view. it is the problem.

**Comment by Cudok** [comment]
thx, for your answers.

Regarding path kwargs, when a new kwarg is used, the ebcpy respectively dymola_api.py must be adapted, right?
This I like to avoid. Is there another possibility?

Regarding libraries: the dymola.sh adds paths to load  (old) system libraries, like libicui18n.so.60, which are part of the dymola installation. 

I looked into the dockerfile bim2sim is using. Here I find a symlink of the dymola.sh to /usr/local/bin/dymola. Maybe I will try this.

**Comment by FWuellhorst** [comment]
Ah ok,  if you use the Dockerfile from bim2sim, it will be similar to the AixLib ci. Here we use:
```
        if "linux" in sys.platform:
            dymola_path = "/usr/local"
            dymola_interface_path = "/opt/dymola-2022-x86_64/Modelica/Library/python_interface/dymola.egg"
```
for kwargs.

**Comment by DaJansenGit** [comment]
@Cudok and I discussed this in recent meeting. From my understanding using dymola.sh should also work with our dymola docker installation. Here is a screenshot from the setup in the dymola container. As you can see the dymola.sh exists and links correctly to the dymola installation. Also running the dymola.sh works
![image](https://github.com/RWTH-EBC/ebcpy/assets/27726960/8ca13512-5004-465a-955b-8e84a7f4dbf5)

You can also see in the [Dockerfile](https://git.rwth-aachen.de/EBC/EBC_intern/dymola-docker/-/blame/master/Dockerfile#L62) that the symlink is created: `ln -s /opt/${DYM_FOLDER}/bin64/dymola.sh /usr/local/bin/dymola && \`

As different Linux systems use different setups, we should make ebcpy usable "out of the box" for most of them. As @Cudok mentioned, he followed the official guideline installing Dymola under Linux (which we apparently didn't in our dockerfile) and this states to use alien which (could you add some information here @Cudok?)

**Comment by Cudok** [comment]
As @DaJansenGit  mentioned, it is recommend to use alien to install the dymola rpm package in the full user manual  (part of the installation see /documentation/). Following you find the relevant part from the full user manual:

17.2.1 Installing Dymola
Dymola for Linux is distributed as an RPM package. The package is installed using the
command
`rpm –i name-of-distribution.rpm`
Optional libraries are installed through separate RPM files.
For installation on e.g. Debian or Kubuntu systems conversion to the deb format is required
using the alien command:
`alien –cki name-of-distribution.rpm`

**Comment by FWuellhorst** [comment]
We should definitely follow the official guideline as a default. I will create a fix for this

**Comment by Cudok** [comment]
thx, now (using ebcpy 0.3.11) it is working out of the box, also for my setup
