### ISSUE TITLE
scipy.io.matlab.mio_utils is deprecated, resulting in ebcpy not working anymore

### ISSUE THREAD

**Issue by jkriwet** [RWTH-EBC/ebcpy#132]
in `ebcpy.modelica.simres.py`, the following import is done

`from scipy.io.matlab.mio_utils import chars_to_strings`

This is used only in one function:
```
def get_strings(str_arr):
    """Return a list of strings from a character array.

    Strip the whitespace from the right and recode it as utf-8.
    """
    return [line.rstrip(' \0').encode('latin-1').decode('utf-8')
            for line in chars_to_strings(str_arr)]
```

`scipy.io.matlab.mio_utils` is deprecated and the requirements state `scipy>=1.5.4`. Since simres.py is imported in data_types, basically nothing works when installing ebcpy in a new, clean environment (where scipy is not installed already, which it probably is in most environments, version 1.11 seems to still work, even though already giving a deprecation warning)

**Comment by FWuellhorst** [comment]
I fixed the issue, should work

**Comment by jkriwet** [comment]
Works now, thank you!
