### ISSUE TITLE
setup.py does not exclude tests

### ISSUE THREAD

**Issue by tstorek** [RWTH-EBC/ebcpy#32]
The current `setup.py` does use automatic package discovery for installation. However, the current line does also discover the tests as packages. 

```
packages=setuptools.find_packages(exclude=['img']),
```

Hence, they will be installed as package as well. This behavior is not usually not wanted.

The line should probably be:
```
packages=setuptools.find_packages(exclude=['tests','tests.*','img']),
```

**Comment by saaiiravi** [comment]
Hi @tstorek 


Please check my PR for this issue.
