### ISSUE TITLE
Refactor cd to cwd?

### ISSUE THREAD

**Issue by FWuellhorst** [RWTH-EBC/ebcpy#61]
We use cd for current directory, but in CLI it means change directory. Maybe we should switch to cwd. 
For convenience, both should be available for some versions using a deprication warning.

**Comment by tstorek** [comment]
I think that it worth to think about it. I think it sometimes also depends on the function itself. Hence, we need to check if `cd` always is used as `current working directory (cwd)` .

**Comment by FWuellhorst** [comment]
`working_directory` seems more clear, as cwd could confuse with the cwd of python.
